#!/bin/bash
sh ./present_cu_aut_01_inner.sh
sh ./present_cu_win_01_inner.sh
sh ./present_cu_spr_01_inner.sh
sh ./present_cu_sum_01_inner.sh
sh ./present_cu_aut_02_inner.sh
sh ./present_cu_win_02_inner.sh
sh ./present_cu_spr_02_inner.sh
sh ./present_cu_sum_02_inner.sh
sh ./present_cu_aut_03_inner.sh
sh ./present_cu_win_03_inner.sh
sh ./present_cu_spr_03_inner.sh
sh ./present_cu_sum_03_inner.sh
sh ./present_cu_aut_04_inner.sh
sh ./present_cu_win_04_inner.sh
sh ./present_cu_spr_04_inner.sh
sh ./present_cu_sum_04_inner.sh
sh ./present_cu_aut_05_inner.sh
sh ./present_cu_win_05_inner.sh
sh ./present_cu_spr_05_inner.sh
sh ./present_cu_sum_05_inner.sh
sh ./present_cu_aut_06_inner.sh
sh ./present_cu_win_06_inner.sh
sh ./present_cu_spr_06_inner.sh
sh ./present_cu_sum_06_inner.sh
sh ./present_cu_aut_07_inner.sh
sh ./present_cu_win_07_inner.sh
sh ./present_cu_spr_07_inner.sh
sh ./present_cu_sum_07_inner.sh
sh ./present_cu_aut_08_inner.sh
sh ./present_cu_win_08_inner.sh
sh ./present_cu_spr_08_inner.sh
sh ./present_cu_sum_08_inner.sh
sh ./present_cu_aut_09_inner.sh
sh ./present_cu_win_09_inner.sh
sh ./present_cu_spr_09_inner.sh
sh ./present_cu_sum_09_inner.sh
sh ./present_cu_aut_10_inner.sh
sh ./present_cu_win_10_inner.sh
sh ./present_cu_spr_10_inner.sh
sh ./present_cu_sum_10_inner.sh
sh ./present_cu_aut_11_inner.sh
sh ./present_cu_win_11_inner.sh
sh ./present_cu_spr_11_inner.sh
sh ./present_cu_sum_11_inner.sh
sh ./present_cu_aut_12_inner.sh
sh ./present_cu_win_12_inner.sh
sh ./present_cu_spr_12_inner.sh
sh ./present_cu_sum_12_inner.sh
sh ./present_cu_aut_13_inner.sh
sh ./present_cu_win_13_inner.sh
sh ./present_cu_spr_13_inner.sh
sh ./present_cu_sum_13_inner.sh
sh ./present_cu_aut_14_inner.sh
sh ./present_cu_win_14_inner.sh
sh ./present_cu_spr_14_inner.sh
sh ./present_cu_sum_14_inner.sh
sh ./present_cu_aut_15_inner.sh
sh ./present_cu_win_15_inner.sh
sh ./present_cu_spr_15_inner.sh
sh ./present_cu_sum_15_inner.sh
sh ./present_cu_aut_16_inner.sh
sh ./present_cu_win_16_inner.sh
sh ./present_cu_spr_16_inner.sh
sh ./present_cu_sum_16_inner.sh
sh ./present_cu_aut_17_inner.sh
sh ./present_cu_win_17_inner.sh
sh ./present_cu_spr_17_inner.sh
sh ./present_cu_sum_17_inner.sh
sh ./present_cu_aut_18_inner.sh
sh ./present_cu_win_18_inner.sh
sh ./present_cu_spr_18_inner.sh
sh ./present_cu_sum_18_inner.sh
sh ./present_cu_aut_19_inner.sh
sh ./present_cu_win_19_inner.sh
sh ./present_cu_spr_19_inner.sh
sh ./present_cu_sum_19_inner.sh
sh ./present_cu_aut_20_inner.sh
sh ./present_cu_win_20_inner.sh
sh ./present_cu_spr_20_inner.sh
sh ./present_cu_sum_20_inner.sh
sh ./present_cd_aut_01_inner.sh
sh ./present_cd_win_01_inner.sh
sh ./present_cd_spr_01_inner.sh
sh ./present_cd_sum_01_inner.sh
sh ./present_cd_aut_02_inner.sh
sh ./present_cd_win_02_inner.sh
sh ./present_cd_spr_02_inner.sh
sh ./present_cd_sum_02_inner.sh
sh ./present_cd_aut_03_inner.sh
sh ./present_cd_win_03_inner.sh
sh ./present_cd_spr_03_inner.sh
sh ./present_cd_sum_03_inner.sh
sh ./present_cd_aut_04_inner.sh
sh ./present_cd_win_04_inner.sh
sh ./present_cd_spr_04_inner.sh
sh ./present_cd_sum_04_inner.sh
sh ./present_cd_aut_05_inner.sh
sh ./present_cd_win_05_inner.sh
sh ./present_cd_spr_05_inner.sh
sh ./present_cd_sum_05_inner.sh
sh ./present_cd_aut_06_inner.sh
sh ./present_cd_win_06_inner.sh
sh ./present_cd_spr_06_inner.sh
sh ./present_cd_sum_06_inner.sh
sh ./present_cd_aut_07_inner.sh
sh ./present_cd_win_07_inner.sh
sh ./present_cd_spr_07_inner.sh
sh ./present_cd_sum_07_inner.sh
sh ./present_cd_aut_08_inner.sh
sh ./present_cd_win_08_inner.sh
sh ./present_cd_spr_08_inner.sh
sh ./present_cd_sum_08_inner.sh
sh ./present_cd_aut_09_inner.sh
sh ./present_cd_win_09_inner.sh
sh ./present_cd_spr_09_inner.sh
sh ./present_cd_sum_09_inner.sh
sh ./present_cd_aut_10_inner.sh
sh ./present_cd_win_10_inner.sh
sh ./present_cd_spr_10_inner.sh
sh ./present_cd_sum_10_inner.sh
sh ./present_cd_aut_11_inner.sh
sh ./present_cd_win_11_inner.sh
sh ./present_cd_spr_11_inner.sh
sh ./present_cd_sum_11_inner.sh
sh ./present_cd_aut_12_inner.sh
sh ./present_cd_win_12_inner.sh
sh ./present_cd_spr_12_inner.sh
sh ./present_cd_sum_12_inner.sh
sh ./present_cd_aut_13_inner.sh
sh ./present_cd_win_13_inner.sh
sh ./present_cd_spr_13_inner.sh
sh ./present_cd_sum_13_inner.sh
sh ./present_cd_aut_14_inner.sh
sh ./present_cd_win_14_inner.sh
sh ./present_cd_spr_14_inner.sh
sh ./present_cd_sum_14_inner.sh
sh ./present_cd_aut_15_inner.sh
sh ./present_cd_win_15_inner.sh
sh ./present_cd_spr_15_inner.sh
sh ./present_cd_sum_15_inner.sh
sh ./present_cd_aut_16_inner.sh
sh ./present_cd_win_16_inner.sh
sh ./present_cd_spr_16_inner.sh
sh ./present_cd_sum_16_inner.sh
sh ./present_cd_aut_17_inner.sh
sh ./present_cd_win_17_inner.sh
sh ./present_cd_spr_17_inner.sh
sh ./present_cd_sum_17_inner.sh
sh ./present_cd_aut_18_inner.sh
sh ./present_cd_win_18_inner.sh
sh ./present_cd_spr_18_inner.sh
sh ./present_cd_sum_18_inner.sh
sh ./present_cd_aut_19_inner.sh
sh ./present_cd_win_19_inner.sh
sh ./present_cd_spr_19_inner.sh
sh ./present_cd_sum_19_inner.sh
sh ./present_cd_aut_20_inner.sh
sh ./present_cd_win_20_inner.sh
sh ./present_cd_spr_20_inner.sh
sh ./present_cd_sum_20_inner.sh
sh ./present_cud_aut_01_inner.sh
sh ./present_cud_win_01_inner.sh
sh ./present_cud_spr_01_inner.sh
sh ./present_cud_sum_01_inner.sh
sh ./present_cud_aut_02_inner.sh
sh ./present_cud_win_02_inner.sh
sh ./present_cud_spr_02_inner.sh
sh ./present_cud_sum_02_inner.sh
sh ./present_cud_aut_03_inner.sh
sh ./present_cud_win_03_inner.sh
sh ./present_cud_spr_03_inner.sh
sh ./present_cud_sum_03_inner.sh
sh ./present_cud_aut_04_inner.sh
sh ./present_cud_win_04_inner.sh
sh ./present_cud_spr_04_inner.sh
sh ./present_cud_sum_04_inner.sh
sh ./present_cud_aut_05_inner.sh
sh ./present_cud_win_05_inner.sh
sh ./present_cud_spr_05_inner.sh
sh ./present_cud_sum_05_inner.sh
sh ./present_cud_aut_06_inner.sh
sh ./present_cud_win_06_inner.sh
sh ./present_cud_spr_06_inner.sh
sh ./present_cud_sum_06_inner.sh
sh ./present_cud_aut_07_inner.sh
sh ./present_cud_win_07_inner.sh
sh ./present_cud_spr_07_inner.sh
sh ./present_cud_sum_07_inner.sh
sh ./present_cud_aut_08_inner.sh
sh ./present_cud_win_08_inner.sh
sh ./present_cud_spr_08_inner.sh
sh ./present_cud_sum_08_inner.sh
sh ./present_cud_aut_09_inner.sh
sh ./present_cud_win_09_inner.sh
sh ./present_cud_spr_09_inner.sh
sh ./present_cud_sum_09_inner.sh
sh ./present_cud_aut_10_inner.sh
sh ./present_cud_win_10_inner.sh
sh ./present_cud_spr_10_inner.sh
sh ./present_cud_sum_10_inner.sh
sh ./present_cud_aut_11_inner.sh
sh ./present_cud_win_11_inner.sh
sh ./present_cud_spr_11_inner.sh
sh ./present_cud_sum_11_inner.sh
sh ./present_cud_aut_12_inner.sh
sh ./present_cud_win_12_inner.sh
sh ./present_cud_spr_12_inner.sh
sh ./present_cud_sum_12_inner.sh
sh ./present_cud_aut_13_inner.sh
sh ./present_cud_win_13_inner.sh
sh ./present_cud_spr_13_inner.sh
sh ./present_cud_sum_13_inner.sh
sh ./present_cud_aut_14_inner.sh
sh ./present_cud_win_14_inner.sh
sh ./present_cud_spr_14_inner.sh
sh ./present_cud_sum_14_inner.sh
sh ./present_cud_aut_15_inner.sh
sh ./present_cud_win_15_inner.sh
sh ./present_cud_spr_15_inner.sh
sh ./present_cud_sum_15_inner.sh
sh ./present_cud_aut_16_inner.sh
sh ./present_cud_win_16_inner.sh
sh ./present_cud_spr_16_inner.sh
sh ./present_cud_sum_16_inner.sh
sh ./present_cud_aut_17_inner.sh
sh ./present_cud_win_17_inner.sh
sh ./present_cud_spr_17_inner.sh
sh ./present_cud_sum_17_inner.sh
sh ./present_cud_aut_18_inner.sh
sh ./present_cud_win_18_inner.sh
sh ./present_cud_spr_18_inner.sh
sh ./present_cud_sum_18_inner.sh
sh ./present_cud_aut_19_inner.sh
sh ./present_cud_win_19_inner.sh
sh ./present_cud_spr_19_inner.sh
sh ./present_cud_sum_19_inner.sh
sh ./present_cud_aut_20_inner.sh
sh ./present_cud_win_20_inner.sh
sh ./present_cud_spr_20_inner.sh
sh ./present_cud_sum_20_inner.sh
sh ./present_cr_aut_01_inner.sh
sh ./present_cr_win_01_inner.sh
sh ./present_cr_spr_01_inner.sh
sh ./present_cr_sum_01_inner.sh
sh ./present_cr_aut_02_inner.sh
sh ./present_cr_win_02_inner.sh
sh ./present_cr_spr_02_inner.sh
sh ./present_cr_sum_02_inner.sh
sh ./present_cr_aut_03_inner.sh
sh ./present_cr_win_03_inner.sh
sh ./present_cr_spr_03_inner.sh
sh ./present_cr_sum_03_inner.sh
sh ./present_cr_aut_04_inner.sh
sh ./present_cr_win_04_inner.sh
sh ./present_cr_spr_04_inner.sh
sh ./present_cr_sum_04_inner.sh
sh ./present_cr_aut_05_inner.sh
sh ./present_cr_win_05_inner.sh
sh ./present_cr_spr_05_inner.sh
sh ./present_cr_sum_05_inner.sh
sh ./present_cr_aut_06_inner.sh
sh ./present_cr_win_06_inner.sh
sh ./present_cr_spr_06_inner.sh
sh ./present_cr_sum_06_inner.sh
sh ./present_cr_aut_07_inner.sh
sh ./present_cr_win_07_inner.sh
sh ./present_cr_spr_07_inner.sh
sh ./present_cr_sum_07_inner.sh
sh ./present_cr_aut_08_inner.sh
sh ./present_cr_win_08_inner.sh
sh ./present_cr_spr_08_inner.sh
sh ./present_cr_sum_08_inner.sh
sh ./present_cr_aut_09_inner.sh
sh ./present_cr_win_09_inner.sh
sh ./present_cr_spr_09_inner.sh
sh ./present_cr_sum_09_inner.sh
sh ./present_cr_aut_10_inner.sh
sh ./present_cr_win_10_inner.sh
sh ./present_cr_spr_10_inner.sh
sh ./present_cr_sum_10_inner.sh
sh ./present_cr_aut_11_inner.sh
sh ./present_cr_win_11_inner.sh
sh ./present_cr_spr_11_inner.sh
sh ./present_cr_sum_11_inner.sh
sh ./present_cr_aut_12_inner.sh
sh ./present_cr_win_12_inner.sh
sh ./present_cr_spr_12_inner.sh
sh ./present_cr_sum_12_inner.sh
sh ./present_cr_aut_13_inner.sh
sh ./present_cr_win_13_inner.sh
sh ./present_cr_spr_13_inner.sh
sh ./present_cr_sum_13_inner.sh
sh ./present_cr_aut_14_inner.sh
sh ./present_cr_win_14_inner.sh
sh ./present_cr_spr_14_inner.sh
sh ./present_cr_sum_14_inner.sh
sh ./present_cr_aut_15_inner.sh
sh ./present_cr_win_15_inner.sh
sh ./present_cr_spr_15_inner.sh
sh ./present_cr_sum_15_inner.sh
sh ./present_cr_aut_16_inner.sh
sh ./present_cr_win_16_inner.sh
sh ./present_cr_spr_16_inner.sh
sh ./present_cr_sum_16_inner.sh
sh ./present_cr_aut_17_inner.sh
sh ./present_cr_win_17_inner.sh
sh ./present_cr_spr_17_inner.sh
sh ./present_cr_sum_17_inner.sh
sh ./present_cr_aut_18_inner.sh
sh ./present_cr_win_18_inner.sh
sh ./present_cr_spr_18_inner.sh
sh ./present_cr_sum_18_inner.sh
sh ./present_cr_aut_19_inner.sh
sh ./present_cr_win_19_inner.sh
sh ./present_cr_spr_19_inner.sh
sh ./present_cr_sum_19_inner.sh
sh ./present_cr_aut_20_inner.sh
sh ./present_cr_win_20_inner.sh
sh ./present_cr_spr_20_inner.sh
sh ./present_cr_sum_20_inner.sh
