#!/bin/bash
sh ./present_cu_aut_01_inner.sh
sh ./present_cu_win_01_inner.sh
sh ./present_cu_spr_01_inner.sh
sh ./present_cu_sum_01_inner.sh
sh ./present_cu_aut_08_inner.sh
sh ./present_cu_win_08_inner.sh
sh ./present_cu_spr_08_inner.sh
sh ./present_cu_sum_08_inner.sh
sh ./present_cu_aut_16_inner.sh
sh ./present_cu_win_16_inner.sh
sh ./present_cu_spr_16_inner.sh
sh ./present_cu_sum_16_inner.sh
sh ./present_cd_aut_01_inner.sh
sh ./present_cd_win_01_inner.sh
sh ./present_cd_spr_01_inner.sh
sh ./present_cd_sum_01_inner.sh
sh ./present_cd_aut_08_inner.sh
sh ./present_cd_win_08_inner.sh
sh ./present_cd_spr_08_inner.sh
sh ./present_cd_sum_08_inner.sh
sh ./present_cd_aut_16_inner.sh
sh ./present_cd_win_16_inner.sh
sh ./present_cd_spr_16_inner.sh
sh ./present_cd_sum_16_inner.sh
sh ./present_cud_aut_01_inner.sh
sh ./present_cud_win_01_inner.sh
sh ./present_cud_spr_01_inner.sh
sh ./present_cud_sum_01_inner.sh
sh ./present_cud_aut_08_inner.sh
sh ./present_cud_win_08_inner.sh
sh ./present_cud_spr_08_inner.sh
sh ./present_cud_sum_08_inner.sh
sh ./present_cud_aut_16_inner.sh
sh ./present_cud_win_16_inner.sh
sh ./present_cud_spr_16_inner.sh
sh ./present_cud_sum_16_inner.sh
sh ./present_cr_aut_01_inner.sh
sh ./present_cr_win_01_inner.sh
sh ./present_cr_spr_01_inner.sh
sh ./present_cr_sum_01_inner.sh
sh ./present_cr_aut_08_inner.sh
sh ./present_cr_win_08_inner.sh
sh ./present_cr_spr_08_inner.sh
sh ./present_cr_sum_08_inner.sh
sh ./present_cr_aut_16_inner.sh
sh ./present_cr_win_16_inner.sh
sh ./present_cr_spr_16_inner.sh
sh ./present_cr_sum_16_inner.sh
